# Generated by Django 3.0.3 on 2020-04-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_boolvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='boolValue',
        ),
    ]
